name: CI
"on":
    pull_request: {}
    push:
        branches:
            - master

jobs:
    unit:
        name: Smoke Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Pack
              uses: buildpacks/github-actions/setup-pack@v3.1.0
            - name: Run Tests
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                make test
