name: CI
"on":
    pull_request: {}
    push:
        branches:
            - main

jobs:
    unit:
        name: Smoke Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Pack
              uses: buildpacks/github-actions/setup-pack@v3.1.0
            - name: Run Tests
              run: make test
